name: Release
on:  
  push:    
    branches: [ master, testlernanew ]
jobs:  
  release:   
    permissions:
      contents: read
      pages: write
      id-token: write 
      env:          
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} 
    name: Release    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@master      
      - uses: actions/setup-node@v1        
        with:          
          node-version: "18.x" 
      - run:  npm i         
      - run: lerna exec --concurrency 1 -- npx semantic-release -e semantic-release-monorepo   
            
         
           
